spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: idyllo
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  mvc:
    favicon:
      enabled: false
  redis:
    host: 127.0.0.1
    port: 6379

server:
  servlet:
    context-path: /sell

# Mock String
wechat:
  mpAppId: dhjsklfhjdkasn
  mpAppSecret: dsafdsagfdskldfsfddsdsds
  openAppId: dsfdsgfsgfdggf
  openAppSecret: dsgdsfgcvdsfd
  templateId:
    orderStatus: dskjafdjksbgjdfksfjidns

# Mock String
project-url:
  wechatMpAuthorize: http://snap.e4
  wechatOpenAuthorize: http://snap.e4
  sell: http://localhost:8080

